##*
##* SafeAuth 1.0
##* Система авторизации
###
### Автор - MrBrikster
###
### Версия сервера - 1.9
###
###

### Данные для подключения к базе данных
sql:
  username: root
  password: ''
  hostname: 127.0.0.1
  database: safeauth
  port: 3306

# Блокировать все команды, кроме написанных в спике "allowedCommands"?
blockCommands: true

# Максимально допустимая длина никнейма
maxNameLength: 16

# Максимальное количество ошибок в наборе пароля
maxErrors: 3

# Допустимые в никнеймах символы (В нижнем регистре)
allowedSymbols: '[a-zA-Z0-9_]*'

# Разрешённые команды
allowedCommands:
- l
- login
- reg
- register

# Режим прокси для переключения между серверами (BUNGEE или LILYPAD)
proxy: BUNGEE

# Главный сервер, на который будет происходить телепортация после авторизации
mainServer: Survival

# Режим отладки
debug: false

# Длина сессии в секундах (По-умолчанию - 3 дня). 0 для отключения сессий.
sessionTime: 259200

# Использовать шифрование SHA-256 (В отличии от SHA-256(MD5(пароль) + SHA-256(пароль))). Нужно для перехода с AuthMe или прочих.
useSha256: false
